name: weatherapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  location: ^4.2.0
  country_state_city_picker: ^1.2.8
  flutter_spinkit: ^5.2.0
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  intl: ^0.17.0

#  google_places_flutter: ^2.0.5
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/